version: "3"

services:
        web:
                build: .
                command: python manage.py runserver 0:1234
                ports:
                        - 1234:1234
                volumes:
                        - ./:/web
                networks:
                        - backend


networks:
        backend:        
